#!/usr/bin/env python3
"""Generate hefermotor/parse/token_kind.pony from ponyc's lexer tables.

The token kinds a Pony lexer can produce are ponyc's `symbols` and
`keywords` tables, plus the tokens whose text varies, plus the kinds in
neither table: the whitespace and comments ponyc skips, and the
end-of-source and error markers its lexer builds without a table entry.
The newline forms come from ponyc's `newline_symbols`.

Re-run this when ponyc's tables change, through `make regen-token-kinds
PONYC_SRC=<ponyc checkout>`. `lexer.c` is read from the checkout's HEAD,
not its working tree, so the commit and the SHA-256 the generated file's
header names describe one file.

    tools/tokens/gen_token_kinds.py <ponyc checkout> <output file>

The output file is written only once generation has succeeded.
"""
import hashlib
import subprocess
import re
import sys

# Tokens the lexer produces whose text is not fixed by their kind, and so is
# not in any of ponyc's tables.
VARIABLE = [
    ("TK_ID", "an identifier"),
    ("TK_STRING", "a string literal"),
    ("TK_INT", "an integer literal"),
    ("TK_FLOAT", "a float literal"),
]

# Kinds in neither of ponyc's tables: the trivia ponyc skips and a lossless
# tree keeps, and the end and error markers ponyc's lexer builds directly.
EXTRA = [
    ("TK_WHITESPACE", "a run of spaces, tabs or newlines"),
    ("TK_LINE_COMMENT", "a `//` comment, up to but not including the newline"),
    ("TK_NESTED_COMMENT", "a `/* */` comment, which may nest"),
    ("TK_EOF", "the end of the source"),
    ("TK_LEX_ERROR", "bytes the lexer could not interpret"),
]


def camel(tk):
    """TK_LSHIFT_TILDE -> TkLshiftTilde"""
    return "Tk" + "".join(p.capitalize() for p in tk[3:].split("_"))


# Kinds in ponyc's `symbols` table that its scan can never produce because an
# earlier entry has the same text, and that `newline_symbols` does not produce
# either; ponyc's parser makes them.
PARSER_ONLY = {"TK_UNARY_MINUS"}


def c_unescape(s):
    unknown = re.search(r'\\[^\\"]', s)
    if unknown is not None:
        raise SystemExit("unsupported escape in table entry: " + s)
    return s.replace("\\\\", "\\").replace('\\"', '"')


def pony_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def table(src, name):
    m = re.search(
        r"static const lextoken_t %s\[\] =\s*\{(.*?)\n\};" % name, src, re.S)
    if m is None:
        raise SystemExit("could not find table: " + name)
    body = re.sub(r"//[^\n]*|/\*.*?\*/", "", m.group(1), flags=re.S)
    return [(c_unescape(t), i) for t, i in
            re.findall(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*(TK_[A-Z0-9_]+)\s*\}',
                       body)]


def newline_forms(src):
    m = re.search(r"static token_id newline_symbols\(.*?\n\}", src, re.S)
    if m is None:
        raise SystemExit("could not find newline_symbols")
    return re.findall(r"case (TK_[A-Z0-9_]+):\s*return (TK_[A-Z0-9_]+);",
                      m.group(0))


def git(checkout, *args):
    try:
        return subprocess.run(["git", "-C", checkout] + list(args),
                              capture_output=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError) as e:
        stderr = getattr(e, "stderr", b"") or b""
        raise SystemExit("%s: %s" % (checkout, stderr.decode().strip()
                                     or str(e)))


def main(checkout):
    raw = git(checkout, "show", "HEAD:src/libponyc/ast/lexer.c")
    commit = git(checkout, "rev-parse", "--short=9", "HEAD").decode().strip()
    digest = hashlib.sha256(raw).hexdigest()
    src = raw.decode()
    symbols = table(src, "symbols")
    keywords = table(src, "keywords")
    forms = newline_forms(src)

    out = []
    w = out.append
    w("// Token kinds, and the fixed text of those that have any.")
    w("//")
    w("// Generated by `tools/tokens/gen_token_kinds.py` from ponyc's")
    w("// `src/libponyc/ast/lexer.c` at commit %s (sha256 of the file:"
      % commit)
    w("// %s)." % digest)
    w("// The kinds are ponyc's `symbols` and `keywords` tables verbatim,")
    w("// plus the tokens whose text varies, plus the trivia ponyc skips and")
    w("// the end and error markers it builds without a table entry. Do not")
    w("// edit by hand: `make regen-token-kinds PONYC_SRC=<checkout>`.")
    w("")

    entries = []  # (pony name, fixed text or None, docstring)
    tk_of = {}    # pony name -> ponyc's TK_ name
    for text, tk in symbols:
        entries.append((camel(tk), text, "The `%s` symbol." % text))
        tk_of[camel(tk)] = tk
    for text, tk in keywords:
        entries.append((camel(tk), text, "The `%s` keyword." % text))
        tk_of[camel(tk)] = tk
    for tk, desc in VARIABLE + EXTRA:
        entries.append((camel(tk), None, "%s." % desc.capitalize()))
        tk_of[camel(tk)] = tk

    seen = {}
    for name, text, doc in entries:
        if name in seen:
            raise SystemExit("duplicate kind: " + name)
        seen[name] = True
        w("primitive %s" % name)
        w('  """')
        w("  %s" % doc)
        w('  """')
        w('  fun name(): String val => "%s"' % name)
        w('  fun ponyc_name(): String val => "%s"' % tk_of[name])
        if text is None:
            w("  fun text(): (String val | None) => None")
        else:
            w('  fun text(): (String val | None) => "%s"' % pony_escape(text))
        w("")

    names = [n for n, _, _ in entries]
    w("type TokenKind is")
    for i, n in enumerate(names):
        lead = "  ( " if i == 0 else "  | "
        w(lead + n)
    w("  )")
    w('  """')
    w("  Every kind of token the lexer can produce.")
    w("")
    w("  `text()` is the token's exact source text where the kind fixes it,")
    w("  and `None` where it does not -- an identifier, a literal, a comment,")
    w("  a run of whitespace. Only the latter need their text stored.")
    w('  """')
    w("")

    w("primitive _Keywords")
    w('  """')
    w("  The keyword kind that `s` spells, or `None` when it spells none; for")
    w("  a lexer that has just scanned an identifier-shaped word.")
    w('  """')
    w("  fun apply(s: String box): (TokenKind | None) =>")
    w("    match s")
    for text, tk in keywords:
        w('    | "%s" => %s' % (pony_escape(text), camel(tk)))
    w("    else")
    w("      None")
    w("    end")
    w("")

    # ponyc's scan takes the first entry for a text, so a later entry with
    # the same text -- "(" as TK_LPAREN_NEW -- can never match. Keep the
    # first only.
    scan, dropped = [], []
    seen_text = set()
    for text, tk in symbols:
        if text in seen_text:
            dropped.append((text, tk))
        else:
            seen_text.add(text)
            scan.append((text, tk))
    for text, tk in dropped:
        if tk not in [to for _, to in forms] and tk not in PARSER_ONLY:
            raise SystemExit("%s: `%s` is unreachable" % (tk, text))

    w("primitive _Symbols")
    w('  """')
    w("  The symbols a scanner can reach, in ponyc's table order, which puts")
    w("  a symbol before its prefixes -- `<<~` before `<<` before `<` -- so")
    w("  that taking the first match takes the longest, as ponyc's scan does.")
    w("")
    w("  ponyc's table lists some texts twice and its scan takes the first,")
    w("  so these are the reachable entries only. Absent, and reachable by")
    w("  other means:")
    for text, tk in dropped:
        w("  `%s` as %s." % (text, camel(tk)))
    w('  """')
    w("  fun apply(): Array[(String val, TokenKind)] val =>")
    w("    [")
    for text, tk in scan:
        w('      ("%s", %s)' % (pony_escape(text), camel(tk)))
    w("    ]")
    w("")

    w("primitive _AllTokenKinds")
    w('  """')
    w("  Every token kind, for tests and for anything that must be shown to")
    w("  handle all of them.")
    w('  """')
    w("  fun apply(): Array[TokenKind] val =>")
    w("    [")
    for n in names:
        w("      " + n)
    w("    ]")
    w("")

    w("primitive _NewlineForm")
    w('  """')
    w("  A symbol's newline form. Pony distinguishes a `(` that opens a call")
    w("  from one that opens a grouped expression by whether a newline")
    w("  precedes it; ponyc's `newline_symbols` does this for every symbol")
    w("  that has such a form, and this is that function.")
    w('  """')
    w("  fun apply(k: TokenKind, after_newline: Bool): TokenKind =>")
    w("    if not after_newline then")
    w("      k")
    w("    else")
    w("      match k")
    for frm, to in forms:
        w("      | %s => %s" % (camel(frm), camel(to)))
    w("      else")
    w("        k")
    w("      end")
    w("    end")

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    text = main(sys.argv[1])
    with open(sys.argv[2], "w") as f:
        f.write(text)
