#!/usr/bin/env python3
"""Generate tk_names.h, mapping a ponyc token_id to its enumerator name.

ponyc has no API for the name: `token_id_desc` gives a description. The
names are read from the `token_id` enum in `token.h` of the checkout
named on the command line, so the header matches that checkout.

    tools/agreement/gen_tk_names.py <ponyc checkout> > tk_names.h
"""
import re
import sys


def main(checkout):
    src = open(checkout.rstrip("/") + "/src/libponyc/ast/token.h").read()
    m = re.search(r"typedef enum token_id\s*\{(.*?)\}\s*token_id;", src,
                  re.S)
    if m is None:
        raise SystemExit("could not find the token_id enum")
    body = re.sub(r"//[^\n]*|/\*.*?\*/", "", m.group(1), flags=re.S)
    names = re.findall(r"\b(TK_[A-Z0-9_]+)\b", body)
    out = ["// Generated by tools/agreement/gen_tk_names.py from ponyc's",
           "// src/libponyc/ast/token.h.",
           "static const char* tk_name(token_id id)", "{", "  switch(id)",
           "  {"]
    for name in names:
        out.append('    case %s: return "%s";' % (name, name))
    out += ['    default: return "?";', "  }", "}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    sys.stdout.write(main(sys.argv[1]))
